# Use root/example as user/password credentials

version: '3.1'

services:

  db:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'docker'
      MYSQL_DATABASE: 'docker_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'docker'
    ports:
      - 3306:3306
    # Change this to your local path
    volumes:
      - \db:/var/lib/mysql
